# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170723_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='haha',
        ),
        migrations.AddField(
            model_name='category',
            name='xixi',
            field=models.CharField(default=b'SOME STRING', max_length=100),
        ),
    ]
